services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pc2_grupo5_back-laravel
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - vendor:/var/www/html/vendor
      - storage:/var/www/html/storage
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: host.docker.internal
      DB_PORT: 5433
      DB_DATABASE: supermercadobbdd_pc2
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

volumes:
  vendor:
  storage:
