version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: host.docker.internal
      DB_PORT: 5433
      DB_DATABASE: supermercadobbdd_pc2
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
